
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class formPegawai extends javax.swing.JDialog {
    
    List<Pegawai> listpegawai = new ArrayList<>();

    /**
     * Creates new form formPegawai
     */
    public formPegawai(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        initState();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelId = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelTpt_lahir = new javax.swing.JLabel();
        jLabelTgl_lahir = new javax.swing.JLabel();
        jLabelAlamat = new javax.swing.JLabel();
        jLabelTelepon = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        TxtGender = new javax.swing.JTextField();
        TxtTpt_lahir = new javax.swing.JTextField();
        TxtTgl_lahir = new javax.swing.JTextField();
        TxtAlamat = new javax.swing.JTextField();
        TxtTelepon = new javax.swing.JTextField();
        BtnSimpan = new javax.swing.JButton();
        BtnTambah = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPegawai = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelId.setText("Id");

        jLabelNama.setText("Nama");

        jLabelGender.setText("Gender");

        jLabelTpt_lahir.setText("Tempat Lahir");

        jLabelTgl_lahir.setText("Tanggal Lahir");

        jLabelAlamat.setText("Alamat");

        jLabelTelepon.setText("Telepon");

        TxtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGenderActionPerformed(evt);
            }
        });

        TxtTgl_lahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTgl_lahirActionPerformed(evt);
            }
        });

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnEdit.setText("Edit");

        BtnHapus.setText("Hapus");

        tblPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "Gender", "Tempat Lahir", "Tanggal Lahir", "Alamat", "Teleponl"
            }
        ));
        jScrollPane1.setViewportView(tblPegawai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelId)
                            .addComponent(jLabelNama)
                            .addComponent(jLabelGender)
                            .addComponent(jLabelTpt_lahir)
                            .addComponent(jLabelTgl_lahir)
                            .addComponent(jLabelAlamat)
                            .addComponent(jLabelTelepon)
                            .addComponent(BtnSimpan))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnTambah)
                                .addGap(40, 40, 40)
                                .addComponent(BtnEdit)
                                .addGap(37, 37, 37)
                                .addComponent(BtnHapus))
                            .addComponent(TxtId)
                            .addComponent(TxtNama)
                            .addComponent(TxtGender)
                            .addComponent(TxtTpt_lahir)
                            .addComponent(TxtTgl_lahir)
                            .addComponent(TxtAlamat)
                            .addComponent(TxtTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnEdit, BtnHapus, BtnSimpan, BtnTambah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelId)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama)
                    .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGender)
                    .addComponent(TxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTpt_lahir)
                    .addComponent(TxtTpt_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTgl_lahir)
                    .addComponent(TxtTgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlamat)
                    .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelepon)
                    .addComponent(TxtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnTambah)
                    .addComponent(BtnEdit)
                    .addComponent(BtnHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGenderActionPerformed

    private void TxtTgl_lahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTgl_lahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTgl_lahirActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        
        SwingUtil swingUtil = new SwingUtil();
        swingUtil.setActive  (true, TxtId, TxtNama, TxtGender, TxtTpt_lahir, 
                    TxtTgl_lahir, TxtAlamat, TxtTelepon);
        BtnSimpan.setEnabled(true);
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
       String TxtId = this.TxtId.getText();
       String TxtNama= this.TxtNama.getText();
       String TxtGender = this.TxtGender.getText();
       String TxtTpt_lahir = this.TxtTpt_lahir.getText();
       String TxtTgl_lahir = this.TxtTgl_lahir.getText();
       String TxtAlamat = this.TxtAlamat.getText();
       String TxtTelepon = this.TxtTelepon.getText();
       
       Pegawai  pegawai= new Pegawai (TxtId,TxtNama,TxtGender,TxtTpt_lahir,
                                TxtTgl_lahir, TxtAlamat, TxtTelepon);
 
       listpegawai.add (pegawai);
       tblPegawai.setModel(new TabelPegawai (listpegawai));
       
       initState();
    }//GEN-LAST:event_BtnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formPegawai dialog = new formPegawai(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtGender;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtTelepon;
    private javax.swing.JTextField TxtTgl_lahir;
    private javax.swing.JTextField TxtTpt_lahir;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelTelepon;
    private javax.swing.JLabel jLabelTgl_lahir;
    private javax.swing.JLabel jLabelTpt_lahir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPegawai;
    // End of variables declaration//GEN-END:variables

    private void initState() {
        SwingUtil swingUtil = new SwingUtil ();
        swingUtil.setActive (false,  TxtId,  TxtNama,  TxtGender,  TxtTpt_lahir,  TxtTgl_lahir,  TxtAlamat,  TxtTelepon);
        swingUtil.setActive(false, BtnEdit, BtnHapus, BtnSimpan);
    }

    private void tampilData() {
       
        
       
    
    }
}
